[cols="2,3", frame=none, grid=rows]
|===
2+^h|*C_TEMPORAL_DEFINITIONS*

2+a|Definitions related to `C_TEMPORAL` constraints.

2+h|*Attributes*

|*valid_date_constraint_patterns*: `xref:BASE:foundation_types:structure_types.adoc#_list_class[List]<xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]>` [1..1]
a|List of allowed date constraints. Contains the values:

```
"YYYY-MM-DD"    -- full date required
"YYYY-MM-??"    -- day optional
"YYYY-MM-XX"    -- day prohibited
"YYYY-??-??"    -- any partial or full date
"YYYY-??-XX"    -- day prohibited
"YYYY-XX-XX"    -- only prohibited
```

|*valid_date_constraint_replacements*: `xref:BASE:foundation_types:structure_types.adoc#_hash_class[Hash]<xref:BASE:foundation_types:primitive_types.adoc#_string_class[String],xref:BASE:foundation_types:structure_types.adoc#_list_class[List]<xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]>>` [1..1]
a|List of allowed date constraint replacements e.g. in specialised archetype. Contains the values:

----
"YYYY-MM-DD": [],

"YYYY-MM-??": ["YYYY-MM-DD", 
               "YYYY-MM-XX"],

"YYYY-MM-XX": [],

"YYYY-??-??": ["YYYY-MM-??",
               "YYYY-MM-DD",
               "YYYY-MM-XX",
               "YYYY-??-XX",
               "YYYY-XX-XX"],

"YYYY-??-XX": ["YYYY-MM-XX", 
              "YYYY-XX-XX"],

"YYYY-XX-XX": []
----

In the above, an empty list value indicates no replacements possible.

|*valid_time_constraint_patterns*: `xref:BASE:foundation_types:structure_types.adoc#_list_class[List]<xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]>` [1..1]
a|List of allowed time constraints. Contains the values:

```
"HH:MM:SS"    -- full time required
"HH:MM:??"    -- seconds optional
"HH:MM:XX"    -- minutes required, seconds prohibited
"HH:??:??"    -- minutes and seconds optional
"HH:??:XX"    -- minutes optional, seconds prohibited
```

|*valid_time_constraint_replacements*: `xref:BASE:foundation_types:structure_types.adoc#_hash_class[Hash]<xref:BASE:foundation_types:primitive_types.adoc#_string_class[String],xref:BASE:foundation_types:structure_types.adoc#_list_class[List]<xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]>>` [1..1]
a|List of allowed time constraint replacements e.g. in specialised archetype. Contains the values:

----
"HH:MM:SS": [],

"HH:MM:??": ["HH:MM:SS",
             "HH:MM:XX"],

"HH:MM:XX": [],

"HH-??-??": ["HH:MM:??",
             "HH:MM:SS",
             "HH:MM:XX",
             "HH:??:XX"],

"HH-??-XX": ["HH:MM:XX"]
----

In the above, an empty list value indicates no replacements possible.

|*valid_date_time_constraint_patterns*: `xref:BASE:foundation_types:structure_types.adoc#_list_class[List]<xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]>` [1..1]
a|List of allowed date/time constraints. Contains the values:

```
"YYYY-MM-DDTHH:MM:SS"    -- full date/time required
"YYYY-MM-DDTHH:MM:??"    -- seconds optional
"YYYY-MM-DDTHH:MM:XX"    -- seconds prohibited
"YYYY-MM-DDTHH:??:??"    -- minutes and seconds optional
"YYYY-MM-DDTHH:??:XX"    -- minutes optional, seconds prohibited
"YYYY-??-??T??:??:??"    -- any date/time ok
```

|*valid_date_time_constraint_replacements*: `xref:BASE:foundation_types:structure_types.adoc#_hash_class[Hash]<xref:BASE:foundation_types:primitive_types.adoc#_string_class[String],xref:BASE:foundation_types:structure_types.adoc#_list_class[List]<xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]>>` [1..1]
a|List of allowed date/time constraint replacements e.g. in specialised archetype. Contains the values:

----
"YYYY-MM-DDTHH:MM:SS": [],

"YYYY-MM-DDTHH:MM:??": ["YYYY-MM-DDTHH:MM:SS",
                        "YYYY-MM-DDTHH:MM:XX"],

"YYYY-MM-DDTHH:MM:XX": [],

"YYYY-MM-DDTHH:??:??": ["YYYY-MM-DDTHH:??:XX",
                        "YYYY-MM-DDTHH:MM:SS",
                        "YYYY-MM-DDTHH:MM:??",
                        "YYYY-MM-DDTHH:MM:XX"],

"YYYY-MM-DDTHH:??:XX": ["YYYY-MM-DDTHH:MM:XX"],

"YYYY-??-??T??:??:??": ["YYYY-MM-DDTHH:MM:SS",
                        "YYYY-MM-DDTHH:MM:??",
                        "YYYY-MM-DDTHH:MM:XX",
                        "YYYY-MM-DDTHH:??:??",
                        "YYYY-MM-DDTHH:??:XX"]
----

2+h|*Functions*

|*valid_duration_constraint_replacement* ( +
a_dur: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String][1]`, +
other_dur: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String][1]` +
): `xref:BASE:foundation_types:primitive_types.adoc#_boolean_class[Boolean]` [1..1]
a|True if ISO8601 duration string `_other_dur_` contains every character element in `_a_dur_`. For example: 'PYD' (period with year and days only) conforms to 'PYMD', but doesn't conform to 'PY'.

|*valid_iso8601_date_constraint_pattern* ( +
s: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String][1]` +
): `xref:BASE:foundation_types:primitive_types.adoc#_boolean_class[Boolean]` [1..1]
a|True if string literal like `"yyyy-MM-dd"` containing `"XX"` or `"??"` in `MM` or `dd` slots in pattern constraint is in `_valid_date_constraint_patterns_`.

|*valid_iso8601_time_constraint_pattern* ( +
s: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String][1]` +
): `xref:BASE:foundation_types:primitive_types.adoc#_boolean_class[Boolean]` [1..1]
a|True if string literal like `"hh:mm:ss[.ssss]"` containing `"XX"` or `"??"` in `mm` or `ss` slots in pattern constraint is in `_valid_time_constraint_patterns_`.

|*valid_iso8601_date_time_constraint_pattern* ( +
s: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String][1]` +
): `xref:BASE:foundation_types:primitive_types.adoc#_boolean_class[Boolean]` [1..1]
a|True if string literal in form `"yyyy-MM-dd hh:mm:ss[.ssss]"` containing `"XX"` or `"??"` in variable slots in pattern constraint is in `_valid_date_time_constraint_patterns_`.

|*valid_iso8601_duration_constraint_pattern* ( +
s: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String][1]` +
): `xref:BASE:foundation_types:primitive_types.adoc#_boolean_class[Boolean]` [1..1]
a|True if string in form `P[Y&#124;y][M&#124;m][W&#124;w][D&#124;d][T[H&#124;h][M&#124;m][S&#124;s]]` (note: allowing 'W' to be mixed in is an openEHR deviation of ISO 8601).
|===
